# flow/states.py

VERIFICATION = "VERIFICATION"
PERMISSION = "PERMISSION"
OUTSTANDING = "OUTSTANDING"
WAIVER = "WAIVER"
SETTLEMENT = "SETTLEMENT"
EMI = "EMI"
TOKEN = "TOKEN"
SAVE_COMMITMENT = "SAVE_COMMITMENT"
PAYMENT_INSTRUCTIONS = "PAYMENT_INSTRUCTIONS"
CLOSING = "CLOSING"
END = "END"